config/routes.rb
Rails.application.routes.draw do
  resources :autocompletes
  devise_for :users
  root to: 'pages#home'

  resources :favorites
  get 'pages/autocomplete', to: 'pages#autocomplete'
  get 'results_details', to: 'results_details#results_details'

  resources :searches

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/autocomplete.rb
class Autocomplete < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user

  def net_rental_yield
    if !property_taxe.nil? && !work.nil? && !insurance.nil? && !total_rent.nil?
      net_rental_yield = ((total_rent*12)/(price + property_taxe + (work/12) + insurance))*(100)
    # elsif property_taxe && work && insurance && total_rent = nil
    else
      net_rental_yield = rendement
    end
  end

  def net_taxe_return
    if !total_rent.nil? && !monthy_loan.nil? && !rental_charges.nil?
      net_taxe_return = total_rent - monthy_loan - rental_charges
    # elsif property_taxe && work && insurance && total_rent = nil
    else
      net_rental_yield
    end
  end
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :search
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :searches
  has_many :favorites
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    new_search_path
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :create

  def index
    @favorites = Favorite.where(user: current_user)
    @favorites = Favorite.all
    @markers = @favorites.map do |favorite|
      {
        lat: favorite.lat,
        lng: favorite.long
      }
    end
  end

  # GET /favorites/:id/
  def show
    @favorite = Favorite.find(params[:id])
  end

  def create
    scraped = params[:scraped]
    ap params[:scraped]
    elements = scraped.split("&")
    hash_fav = {}
    elements.each do |el|
      keyval = el.split("=")
      key = keyval[0]
      value = keyval[1]
      case key
      when "price", "rendement", "lat", "lng"
        value = value.to_f
      when "rooms", "surface", "user_id", "avg_rent"
        value = value.to_i
      end
      hash_fav[key.to_sym] = value
    end
    @fav = Favorite.new(hash_fav)

    respond_to do |format|
      if @fav.save
        format.html { redirect_to favorites_path }
        format.js { }
      end
    end
  end

  def update
    @favorite = Favorite.find(params[:id])
    @favorite.update(favorite_params)
    redirect_to favorite_path(@favorite)
  end

  def destroy
    @favorite = Favorite.find(params[:id])
    @favorite.destroy
    redirect_to favorites_path
  end

  private

  def favorite_params
    params.require(:favorite).permit(
      :property_taxe,
      :insurance,
      :total_rent,
      :monthy_loan,
      :rental_charges,
      :total_rent,
      :work,
      :city,
      :urlscrap,
      :avg_rents
    )
  end

  def index_params
    params.require(:favorites).permit(:price, :city, :avg_rents)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :autocomplete]

  def home
  end

  def autocomplete

  end
end

app/controllers/results_details_controller.rb
class ResultsDetailsController < ApplicationController

  def show

  end

  def index

  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def index
    if params[:search].present?
      @results_base = Collecteur.new(search_params, current_user).collecter[:prices]
      @results = @results_base.sort_by { |appt| appt[:returns] }.reverse
    else
      @results = []
    end
  end

  def new
    @search = Search.new
    @user = current_user
  end

  def show
    @search = Search.find(params[:id])
    scrap_lbc_with(
      city: @search.city,
      zipcode: @search.zipcode,
      budget: @search.budget
    )
    @search.update_attributes(last_scrap: DateTime.current)
  end

  def destroy
    @search = Search.find(params[:id])
    @search.destroy
  end

  def create
    scrap_lbc_with(search_params)
    search = Search.new(search_params)
    search.last_scrap = DateTime.current
    search.user = current_user
    search.save
    render 'create.js'
  end

  def update
  end

  def save

  end

  private

  def scrap_lbc_with(attributes)
    @results_base = Collecteur.new(attributes).collecter[:prices]
    @results = @results_base.sort_by { |appt| appt[:returns] }.reverse
    @prices = @results
  end

  def search_params
    params.require(:search).permit(:city, :zipcode, :budget)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/favorites/create.js.erb
var resultCard = document.querySelector("[data-bc-url='<%= @fav.urlscrap %>']");
resultCard.querySelector('.select_info').innerHTML = "<p class='green'>Selectionné</p>"

app/views/favorites/index.html.erb
<div class="container-fluid">
  <div class="main-container-selection">
    <div class="row">
      <div class="col-xs-12 col-md-6 rowcards">

        <div class="favselection">


          <h3 class="fav-title">Ma selection</h3>
          <% @favorites.each do |f| %>
            <div class="appartment">
              <div class="appartment-image">
                <% if f.urlimage.present? %>
                  <img src="<%= f.urlimage %>" alt="">
                <% else %>
                  <img src="https://www.housing.bt/assets/default-apartment(copy)-940bd729ea9cdf1a5cc31a6dd1812b2350e00702e2d384208eb4384e1d274ea4.jpg" alt="">
                <% end %>
              </div>
              <div class="appartment-infos">
                <div class="metrics">
                  <div class="metric main">
                    <h2 class="green"><%= f.rendement.round(2) %> %</h2>
                    <label>Rendement brut</label>
                  </div>
                  <div class="metric">
                    <h2><%= number_to_currency(f.avg_rent, format: "%n %u", unit: "€", delimiter: " ", precision: 0) %> / mois</h2>
                    <label>Loyer potentiel</label>
                  </div>
                </div>

                <hr>

                <h4><%= number_to_currency(f.price, format: "%n %u", unit: "€", delimiter: " ", precision: 0) %></h4>
                <p><%= f.rooms %> pièces, <%= f.surface %>m²</p>
                <p><%= f.city %></p>

                <%= link_to '<i class="fas fa-eye faveyes"></i>'.html_safe, favorite_path(f), id: 'show-favorite' %>

                <%= link_to '<i class="fas fa-trash-alt favtrash"></i>'.html_safe, favorite_path(f), method: :delete, data: {:confirm => 'Confirmez la suppression ?'}, id: 'remove-favorite' %>
              </div>
            </div>









          <% end %>
        </div>

      </div>
      <div class="col-xs-12 col-md-6 sticky">
        <div
          id="map"
          data-markers=" <%= @markers.to_json %>"
        ></div>

      </div>
    </div>
  </div>
</div>

app/views/favorites/show.html.erb
<div class="container">
  <div class="section">
    <div class="row">
      <div class="col-xs-12">
        <div class="detail-appartment">
          <div class="appartment-image">
            <% if @favorite.urlimage.present? %>
              <img src="<%= @favorite.urlimage %>" alt="">
            <% else %>
              <img src="https://www.housing.bt/assets/default-apartment(copy)-940bd729ea9cdf1a5cc31a6dd1812b2350e00702e2d384208eb4384e1d274ea4.jpg" alt="">
            <% end %>
          </div>

          <div class="appartment-infos">
            <h4><%= @favorite.city %></h4>
            <h4><%= number_to_currency(@favorite.price, format: "%n %u", unit: "€", delimiter: " ", precision: 0) %></h4>
            <p><%= @favorite.rooms %> pièces, <%= @favorite.surface %> m²</p>
          </div>

          <a target="_blank" class="btn btn-warning link-appartment" href='<%= @favorite.urlscrap %>'> Voir annonce</a>
        </div>
      </div>
    </div>
  </div>


  <div class="section">
    <div class="row">
      <div class="col-xs-12">
        <h2>Rendement brut</h2>

        <hr>

        <p>Le rendement brut est le plus simple à déterminer, et ce pour une bonne raison. Il ne tient pas compte des charges locatives payées par le bailleur ni de sa taxation. Par conséquent, il suffit de déclarer le loyer annuel au prix d’acquisition pour identifier la rentabilité brute de l’investissement immobilier.</p>
        <p><strong>Exemple de calcul du rendement brut:</strong> un investisseur loue un appartement moyennant un loyer mensuel de 800 euros charges comprises. Il a payé son achat immobilier 200 000 euros, frais d'acquisition inclus. La rentabilité brute de la propriété est donc :</p>
        <br>
        <p class="exemple">(800 x 12/200 000) x 100 = 4,80%</p>
        <br>
        <div class="metric">
          <strong>Rendement brut potentiel : <%= @favorite.rendement.round(2) %> %</strong>
        </div>
      </div>
    </div>
  </div>

  <div class="section">
    <div class="row">
      <div class="col-xs-12">
        <h2>Affiner le calcul de votre rendement</h2>

        <hr>

        <p>Pour aller plus loin, les investisseurs doivent s’intéresser à la rentabilité de leur location en tenant compte des coûts et charges qu’ils doivent supporter tels que l’impôt sur la propriété.</p>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-md-6 col-md-offset-3">
        <br>
        <%= simple_form_for @favorite do |f| %>
          <%= f.input :property_taxe, label: "Taxes foncières - € / an" %>
          <%= f.input :insurance, label: "Assurance - € / an" %>
          <%= f.input :total_rent, label: "Loyer (estimé) - € / mois", hint: "Notre estimation : #{@favorite.avg_rent} €" %>
          <%= f.input :work, label: "Travaux (estimé) - €" %> <br>

          <%= f.submit "Calculer", class: "btn btn-warning" %>
        <% end %>

        <% if @favorite.property_taxe && @favorite.insurance && @favorite.total_rent && @favorite.work %>
        <br><br>
          <div class="metric">
            <strong>Rendement locatif net potentiel : <%= @favorite.net_rental_yield.round(2) %> %</strong>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="section">
    <div class="row">
      <div class="col-xs-12">
        <h2>CashFlow</h2>

        <hr>

        <p>Le Cashflow correspond au rendement net imposable</p>
        <p>Pour calculer le retour sur investissement le plus fidèlement possible, le bailleur doit également tenir compte de ses impôts (ceux-ci ne seront pas calculés ici). C’est le principe du rendement «net-net» ou net d’imposition. Il tient compte de la charge fiscale supportée par l’investisseur, c’est-à-dire de l’imposition des revenus de la propriété.</p>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-md-6 col-md-offset-3">
        <br>
        <%= simple_form_for @favorite do |f| %>
          <%= f.input :monthy_loan, label: "Remboursement de crédit - € / mois" %> €/mois
          <%= f.input :rental_charges, label: "Frais de location - € / an" %>
          <%= f.input :total_rent, label: "Loyer(estimé) - € / mois" %>
          <%= f.submit "Calculer", class: "btn btn-warning" %>
        <% end %>

        <% if @favorite.monthy_loan && @favorite.rental_charges && @favorite.total_rent %>
          <br><br>
          <div class="metric">
            <strong>Pententiel Cashflow : <%= @favorite.net_taxe_return.round(0) %> € / mois</strong>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="Mycashflow" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://mycashflow.me" />
    <meta property="og:image" content='<%= image_url "/assets/images/banner9.jpg", size: "1200x630" %>' />
    <meta property="og:description" content="Trouvez votre investissement locatif" />
    <meta property="og:site_name" content="Mycashflow" />
    <title>My Cash Flow</title>

    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>

    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>

    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

    <script src="https://maps.googleapis.com/maps/api/js?key=
    AIzaSyAZuR-94uFzg2VuikctpXZHBOcFcuX0Wzo
    &libraries=places&callback=initGoogleJs"
    async defer></script>
  </body>
</html>

app/views/pages/home.html.erb
<div class ="homepage" >
  <div class="homebanner">
    <br>
<%= image_tag "logo.png", height: 100 %>
    <h1>Optimisez vos investissements</h1>
    <p>Alerte périodique pour les meilleures opportunités immobilières</p>
    <br>
    <br>
    <div class="btnaccount btn btn-warning">
    <%= link_to "Créer votre compte", new_user_registration_path %>
    </div>
  </div>
    <br>
    <br>
  <div class="findicones">
      <div class="card cardicones">
        <br>

        <svg height="30" width="60"aria-hidden="true" color="#E67E22"data-prefix="fas" data-icon="map-marked-alt" class="svg-inline--fa fa-map-marked-alt fa-w-18" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512"><path fill="currentColor" d="M288 0c-69.59 0-126 56.41-126 126 0 56.26 82.35 158.8 113.9 196.02 6.39 7.54 17.82 7.54 24.2 0C331.65 284.8 414 182.26 414 126 414 56.41 357.59 0 288 0zm0 168c-23.2 0-42-18.8-42-42s18.8-42 42-42 42 18.8 42 42-18.8 42-42 42zM20.12 215.95A32.006 32.006 0 0 0 0 245.66v250.32c0 11.32 11.43 19.06 21.94 14.86L160 448V214.92c-8.84-15.98-16.07-31.54-21.25-46.42L20.12 215.95zM288 359.67c-14.07 0-27.38-6.18-36.51-16.96-19.66-23.2-40.57-49.62-59.49-76.72v182l192 64V266c-18.92 27.09-39.82 53.52-59.49 76.72-9.13 10.77-22.44 16.95-36.51 16.95zm266.06-198.51L416 224v288l139.88-55.95A31.996 31.996 0 0 0 576 426.34V176.02c0-11.32-11.43-19.06-21.94-14.86z" class="icon"></path></svg>
        <h4 class="card">Sélectionnez votre région</h4>
        <p> Vous décidez de la zone qui vous convient, pour trouver votre meilleur investissement.</p>
      </div>
      <div class="card cardicones">
        <br>

        <svg height="40" width="60"aria-hidden="true" color="#E67E22"data-prefix="fas" data-icon="hand-holding-usd" class="svg-inline--fa fa-hand-holding-usd fa-w-17" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 544 512"><path fill="currentColor" d="M257.6 144.3l50 14.3c3.6 1 6.1 4.4 6.1 8.1 0 4.6-3.8 8.4-8.4 8.4h-32.8c-3.6 0-7.1-.8-10.3-2.2-4.8-2.2-10.4-1.7-14.1 2l-17.5 17.5c-5.3 5.3-4.7 14.3 1.5 18.4 9.5 6.3 20.3 10.1 31.8 11.5V240c0 8.8 7.2 16 16 16h16c8.8 0 16-7.2 16-16v-17.6c30.3-3.6 53.3-31 49.3-63-2.9-23-20.7-41.3-42.9-47.7l-50-14.3c-3.6-1-6.1-4.4-6.1-8.1 0-4.6 3.8-8.4 8.4-8.4h32.8c3.6 0 7.1.8 10.3 2.2 4.8 2.2 10.4 1.7 14.1-2l17.5-17.5c5.3-5.3 4.7-14.3-1.5-18.4-9.5-6.3-20.3-10.1-31.8-11.5V16c0-8.8-7.2-16-16-16h-16c-8.8 0-16 7.2-16 16v17.6c-30.3 3.6-53.3 31-49.3 63 2.9 23 20.7 41.3 42.9 47.7zm276.3 183.8c-11.2-10.7-28.5-10-40.3 0L406.4 402c-10.7 9.1-24 14-37.8 14H256.9c-8.3 0-15.1-7.2-15.1-16s6.8-16 15.1-16h73.9c15.1 0 29-10.9 31.4-26.6 3.1-20-11.5-37.4-29.8-37.4H181.3c-25.5 0-50.2 9.3-69.9 26.3L67.5 384H15.1C6.8 384 0 391.2 0 400v96c0 8.8 6.8 16 Ò15.1 16H352c13.7 0 27-4.9 37.8-14l142.8-121c14.4-12.1 15.5-35.3 1.3-48.9z"></path></svg>
        <h4 class="card">Définissez votre budget</h4>
        <p> Vous définissez votre budget maximal pour votre projet.</p>
    </div>
    <div class="card cardicones">
      <br>
        <h4 class="card">
        <svg height="30" width="60"aria-hidden="true" color="#E67E22"data-prefix="fas" data-icon="search-dollar" class="svg-inline--fa fa-search-dollar fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M505.04 442.66l-99.71-99.69c-4.5-4.5-10.6-7-17-7h-16.3c27.6-35.3 44-79.69 44-127.99C416.03 93.09 322.92 0 208.02 0S0 93.09 0 207.98s93.11 207.98 208.02 207.98c48.3 0 92.71-16.4 128.01-44v16.3c0 6.4 2.5 12.5 7 17l99.71 99.69c9.4 9.4 24.6 9.4 33.9 0l28.3-28.3c9.4-9.4 9.4-24.59.1-33.99zm-297.02-90.7c-79.54 0-144-64.34-144-143.98 0-79.53 64.35-143.98 144-143.98 79.54 0 144 64.34 144 143.98 0 79.53-64.35 143.98-144 143.98zm27.11-152.54l-45.01-13.5c-5.16-1.55-8.77-6.78-8.77-12.73 0-7.27 5.3-13.19 11.8-13.19h28.11c4.56 0 8.96 1.29 12.82 3.72 3.24 2.03 7.36 1.91 10.13-.73l11.75-11.21c3.53-3.37 3.33-9.21-.57-12.14-9.1-6.83-20.08-10.77-31.37-11.35V112c0-4.42-3.58-8-8-8h-16c-4.42 0-8 3.58-8 8v16.12c-23.63.63-42.68 20.55-42.68 45.07 0 19.97 12.99 37.81 31.58 43.39l45.01 13.5c5.16 1.55 8.77 6.78 8.77 12.73 0 7.27-5.3 13.19-11.8 13.19h-28.1c-4.56 0-8.96-1.29-12.82-3.72-3.24-2.03-7.36-1.91-10.13.73l-11.75 11.21c-3.53 3.37-3.33 9.21.57 12.14 9.1 6.83 20.08 10.77 31.37 11.35V304c0 4.42 3.58 8 8 8h16c4.42 0 8-3.58 8-8v-16.12c23.63-.63 42.68-20.54 42.68-45.07 0-19.97-12.99-37.81-31.59-43.39z"></path></svg>
        <h4 class="card"> Les meilleures opportunitées</h4>
        <p> Laissez-nous trouver pour vous toutes les meilleures opportunitées</p>
      </div>
    </div>
</div>

app/views/progresses/index.html.erb
<h1>Progresses#index</h1>
<p>Find me in app/views/progresses/index.html.erb</p>

app/views/searches/_latest_searches.html.erb
<h5 class="searches-title">Mes recherches</h5>

<% searches.each do |search| %>
  <div class="searchcard">
    <%= link_to '', search_path(search), class: 'search-link' %>
    <div class="searchcity">
      <h5>
        <%= search.city %>
        <% if search.zipcode.present? %>
          (<%= search.zipcode %>)
        <% end %>
      </h5>
    </div>

    <div class="searchbudget">
      <p><%= number_to_currency(search.budget / 1000, unit: "k€", precision: 0, delimiter: " ", format: "%n %u") %></p>
    </div>

    <div class="searchcard-flex">
      <div class="searchdate">
        <p>
          Dernière recherche il y a <%= time_ago_in_words(search.last_scrap) %>

        </p>
      </div>


     <%= link_to '<i class="far fa-times-circle searchdelete"></i>'.html_safe, search_path(search), remote: true, method: :delete,data: {:confirm => 'Confirmez la suppression ?'} %>
    </div>
  </div>
<% end %>

app/views/searches/_result.html.erb
<div class="appartment" data-bc-url="<%= result[:url] %>">
  <div class="appartment-image">
    <% if result[:image].present? %>
      <img src="<%= result[:image] %>" alt="">
    <% else %>
      <img src="https://www.housing.bt/assets/default-apartment(copy)-940bd729ea9cdf1a5cc31a6dd1812b2350e00702e2d384208eb4384e1d274ea4.jpg" alt="">
    <% end %>
  </div>
  <div class="appartment-infos">
    <div class="metrics">
      <div class="metric main">
        <h2 class="green"><%= result[:returns].round(2) %> %</h2>
        <label>Rendement brut</label>
      </div>
      <div class="metric">
        <h2><%= number_to_currency(result[:avg_rents].round, format: "%n %u", unit: "€", delimiter: " ", precision: 0) %> / mois</h2>
        <label>Loyer potentiel</label>
      </div>
    </div>

    <hr>

    <h4><%= number_to_currency(result[:price], format: "%n %u", unit: "€", delimiter: " ", precision: 0) %></h4>
    <h5><%= result[:subject] %></h5>
    <p><%= pluralize(result[:rooms], "pièce") %>, <%= result[:surface] %>m²</p>

    <% scraped = "urlscrap=#{result[:url]}&urlimage=#{result[:image]}&price=#{result[:price]}&rendement=#{result[:returns]}&rooms=#{result[:rooms]}&surface=#{result[:surface]}&user_id=#{current_user.id}&lat=#{result[:lat]}&long=#{result[:lng]}&city=#{result[:city]}&zipcode=#{result[:zipcode]}&avg_rent=#{result[:avg_rents]}" %>
    <div class="select_info">
      <%= form_tag(favorites_path, method: :post, remote: true) do %>
        <%= hidden_field_tag :scraped, scraped %>
        <%= submit_tag "Selectionnez", class: "btn btn-warning" %>
      <% end %>
    </div>
  </div>
</div>

app/views/searches/_search_form.html.erb
<%= simple_form_for(@search, html: { class: 'form-inline' }) do |f| %>
  <%= f.input "budget", input_html: { id: 'budget', placeholder: "300 000 € " }, label: 'Budget max' %>
  <%= f.input "city", input_html: { id: 'pac-input', placeholder: "Ville ou code postal" }, wrapper_html: { id: "zone" }, label: "Zone" %>
  <%= f.input "zipcode", input_html: { id: 'zipcode' }, as: :hidden %>
  <%= f.submit "Rechercher", id: "button", class: "btn btn-warning" %>
<% end %>

app/views/searches/create.html.erb
<h1>Create.HTML.erb</h1>

<div id="map" style="height: 300px; width: 600px"></div>

<h1>Prices</h1>
<% @prices.each do |appt| %>
<div>
  <%= appt %>
</div>
<% end %>
<br>
<h1>Rents</h1>
<% @rents.each do |appt| %>
<div>
  <%= appt %>
</div>
<% end %>

app/views/searches/create.js.erb
function displayResults() {

  const container = document.getElementById('results');
  container.innerHTML = '';
  let marker;

  <% @results.each do |result| %>
    container.insertAdjacentHTML('beforeend', `<%= j render 'result', result: result %>`)
  <% end %>
}

displayResults();

app/views/searches/destroy.js.erb
function updateLastSearches() {
  const container = document.querySelector('.last-searches');
  container.innerHTML = "<%= j render 'latest_searches', searches: current_user.searches %>";
}

updateLastSearches();

app/views/searches/index.html.erb
<form action="<%= searches_path %>" method="get">
  <div class="formulaire">
    <div class="form-inl">
      <input id="budget" class="controls" name="search[budget]" type="number" placeholder="Budget">
    </div>
    <div class="form-inl">
      <textarea name="search[city]" id="city"></textarea>
    </div>
    <div class="form-inl">
      <textarea name="search[zipcode]" id="zipcode"></textarea>
    </div>
    <div class="form-inl">
      <input id="pac-input" class="controls" type="text" placeholder="Search Box">
    </div>
    <div class="form-inl">
      <input type="submit" id="button">
    </div>
  </div>
</form>

<div class="createpage">
  <%= image_tag "logo.png", height: 200 %>

  <div id="map" style="height: 300px; width: 600px"></div>

  <div id="results">
    <h1><%= @results.size %></h1>
    <% @results.each do |result| %>
      <%= render 'result', result: result %>
    <% end %>
  </div>
</div>

app/views/searches/new.html.erb
<div class="main-container">
  <div class="last-searches">
    <%= render 'latest_searches', searches: current_user.searches %>
  </div>

  <div class="current-search">
    <%= render 'search_form' %>

    <div id="results"></div>
    <div id="loader" class="loader">
      <img src="http://dev.s212147.gridserver.com/images/seckel-ajax-loader.gif" alt="">
    </div>
  </div>
</div>

app/views/searches/show.html.erb
<div class="main-container">
  <div class="last-searches">
    <%= render 'latest_searches', searches: current_user.searches %>
  </div>

  <div class="current-search">
    <%= render 'search_form' %>

    <div id="results">
      <% @results.each do |result| %>
        <%= render 'result', result: result %>
      <% end %>
    </div>
    <div id="loader" class="loader">
      <img src="http://dev.s212147.gridserver.com/images/seckel-ajax-loader.gif" alt="">
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">

  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <i class=""></i>
      <%= link_to "", new_search_path, class: "fas fa-search navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Ma selection", favorites_path , class: "navbar-wagon-item navbar-wagon-link" %>
      <div class="navbar-wagon-item navbar-wagon-link logbuton">
              <%= link_to destroy_user_session_path, method: :delete do %>
               <%= t(".sign_out", default: "Déconnexion") %>
      <% end %>
      </div>
    </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Connexion"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">New search</a></li>
        <li><a href="#">Favorites</a></li>
        <li><a href="#">Log out</a></li>
      </ul>
    </div>
  </div>
</div>